[workspace]
members = [
  "repositories/monorepo-rust-libraries/*",
  "repositories/packages/rust-packages/*"
]

[package]
name = "wisdomstar94-monorepo"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "wisdomstar94-monorepo"
path = "./main.rs"

[dependencies]

