[package]
name = "useful-cli"
version = "0.0.3"
edition = "2021"

[dependencies]
clap = {version = "4.5.23", features = ["derive"] }
encoding_rs = "0.8.35"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
rust_utils = { path = "../../../monorepo-rust-libraries/rust-utils" }
downloader = { path = "../../../monorepo-rust-libraries/downloader" }
flater = { path = "../../../monorepo-rust-libraries/flater" }
file_manager = { path = "../../../monorepo-rust-libraries/file_manager" }
commander = { path = "../../../monorepo-rust-libraries/commander" }
openssl = { version = "0.10.68", features = ["vendored"] }
glob = "0.3.2"