import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import { Providers } from './tanstack-query/providers';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menus = [
    { href: '/' },
    { href: '/test/test1' },
    { href: '/test/test2' },
    { href: '/test/test3' },
    { href: '/test/rsc-combine' },
    { href: '/test/rsc-streaming' },
    { href: '/test/suspense-query' },
    // ..
  ];

  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <div className="w-full flex flex-wrap gap-2 relative">
            {menus.map((item) => {
              return (
                <Link
                  key={item.href}
                  href={item.href}
                  className="inline-flex px-2 py-0.5 text-xs rounded-sm border border-slate-400 cursor-pointer hover:slate-100"
                >
                  {item.href}
                </Link>
              );
            })}
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
