name: react-add-event-listener-ci-cd

on:
  push:
    tags:
      - "react-add-event-listener-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-release-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: corepack enable
      - run: corepack prepare yarn@stable --activate
      - run: yarn install
      - run: yarn monorepo-libraries:build
      - run: yarn @wisdomstar94/react-add-event-listener pack:build
      - run: yarn @wisdomstar94/react-add-event-listener npm:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGE_PUBLISH_KEY_NPM}}
