name: 'wisdomstar94-libraries-docs-ci-cd'

on:
  push:
    tags:
      - 'wisdomstar94-libraries-docs-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - run: corepack enable
      - run: corepack prepare yarn@stable --activate
      - run: yarn install
      - run: yarn @wisdomstar94/wisdomstar94-libraries-docs build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './repositories/frontends/document-frontends/wisdomstar94-libraries-docs/out'

  github-page-deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Docs
        uses: actions/deploy-pages@v4
